# Generated by Django 5.1.4 on 2025-02-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_rename_escricao_longa_produto_descricao_longa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='Produto',
            new_name='produto',
        ),
    ]
