# Generated by Django 5.1.4 on 2025-02-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='produt_id',
            new_name='produto_id',
        ),
    ]
